### ISSUE TITLE
null value at risultatoLista JsonObject

### ISSUE THREAD

**Issue by lrusso96** [LithiumSR/openstud_driver#1]
The method **_getUnpaidTaxes** throws **JsonException** when _risultatoLista_ is null, instead of returning empty _LinkedList_ object.

Note: this could happen in **_getPaidTaxes**, too.

**Comment by LithiumSR** [comment]
It got fixed with your commit (8116c61b3a3a1504b729733037d381d6095bdc23). Thank you :)
