### ISSUE TITLE
Expired password

### ISSUE THREAD

**Issue by lrusso96** [LithiumSR/openstud_driver#3]
It's not handled the case when password is correct, but **expired**, and should be reset. This case should not throw the default exception _Infostud is not working properly_, because it's actually working.

**Comment by LithiumSR** [comment]
Commit 49d73f2969cd2ae6678a8fc02b8fae000c532c0e should have fixed this issue.
I will keep this issue open for now until I run some tests

**Comment by LithiumSR** [comment]
It seems that I misunderstood your issue. Now you can check if an InvalidCredentialsException was thrown because user's account has an expired password. Fixed with commit https://github.com/LithiumSR/openstud_driver/commit/3073ef34adc93f9abf43b1498724a2d67d16abb4
